### ISSUE TITLE
pygatt.lescan() "disables" interface after scan.

### ISSUE THREAD

**Issue by NemoN** [stratosinc/pygatt#4] opened 2014-11-05 15:40 UTC
Every time i use lescan() i must reset the interface to do another scan:

```
>>> pygatt.lescan()
[{'name': 'Nexturn', 'address': 'D0:39:72:A1:D2:58'}, {'name': 'Nexturn', 'address': '90:59:AF:2A:C7:B8'}, {'name': 'Nexturn', 'address': 'D0:39:72:A1:B8:D0'}]

>>> pygatt.lescan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygatt-0.0.1-py2.7.egg/pygatt/pygatt.py", line 22, in lescan
    scan.expect("foooooo", timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/pexpect.py", line 1316, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect.py", line 1330, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect.py", line 1401, in expect_loop
    raise EOF (str(e) + '\n' + str(self))
pexpect.EOF: End Of File (EOF) in read_nonblocking(). Exception style platform.
<pexpect.spawn object at 0xb68bdbf0>
version: 2.4 ($Revision: 516 $)
command: /usr/bin/sudo
args: ['/usr/bin/sudo', 'hcitool', 'lescan']
searcher: searcher_re:
    0: re.compile("foooooo")
buffer (last 100 chars):
before (last 100 chars): Set scan parameters failed: Input/output error
after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 757
child_fd: 3
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

>>> pygatt.reset_bluetooth_controller()
Re-initializing Bluetooth controller

>>> pygatt.lescan()
[{'name': 'Nexturn', 'address': 'D0:39:72:A1:D2:58'}, {'name': 'Nexturn', 'address': '90:59:AF:2A:C7:B8'}, {'name': 'Nexturn', 'address': 'D0:39:72:A1:B8:D0'}]
>>>
```

hcitool works on command line with muliple scans:
```
# hcitool lescan
LE Scan ...
D0:39:72:A1:D2:58 (unknown)
D0:39:72:A1:D2:58 Nexturn
D0:39:72:A1:B8:D0 (unknown)
90:59:AF:2A:C7:B8 (unknown)
90:59:AF:2A:C7:B8 Nexturn
D0:39:72:A1:D2:58 (unknown)
D0:39:72:A1:D2:58 Nexturn
[CTTL+C]

# hcitool lescan
LE Scan ...
D0:39:72:A1:D2:58 (unknown)
D0:39:72:A1:D2:58 Nexturn
D0:39:72:A1:B8:D0 (unknown)
D0:39:72:A1:B8:D0 Nexturn

```

**Comment by peplin** [comment] 2015-06-03 00:16
It's been a *while*, but I did figure out how to fix this - the problem is when running `sudo hcitool lescan` as a subprocess from a non-root Python process, it can't cleanly close it. The solution: https://github.com/stratosinc/pygatt/commit/a69a1cf0db8b0528d23c0c96eee36f5696203450

don't run it as root!

**Closed by peplin** 2015-06-03 00:16 UTC
